local TbFrame = {
	{ id=10000, name="初始头像框", propdesc="初始头像框", type=0, priority=1, openclose=0, param=0 },
	{ id=10001, name="闪耀黄金头像框", propdesc="闪耀黄金头像框，在排位赛达到闪耀黄金段位的证明", type=1, priority=15, openclose=0, param=19 },
	{ id=10002, name="梦幻白金头像框", propdesc="梦幻白金头像框，在排位赛达到梦幻白金段位的证明", type=1, priority=14, openclose=0, param=35 },
	{ id=10003, name="永恒钻石头像框", propdesc="永恒钻石头像框，在排位赛达到永恒钻石段位的证明", type=1, priority=13, openclose=0, param=51 },
	{ id=10004, name="至尊大师头像框", propdesc="至尊大师头像框，在排位赛达到至尊大师段位的证明", type=1, priority=12, openclose=0, param=76 },
	{ id=10005, name="最强王者头像框", propdesc="最强王者头像框，在排位赛达到最强王者段位的证明", type=1, priority=11, openclose=0, param=101 },
	{ id=10006, name="传说王者头像框", propdesc="传说王者头像框，在排位赛达到传说王者段位的证明", type=0, priority=10, openclose=0, param=0 },
	{ id=10007, name="圣诞头像框", propdesc="圣诞节，当然要和朋友们一起战斗啦！", type=0, priority=30, openclose=0, param=0 },
	{ id=10008, name="西亚专属头像框", propdesc="合金计划·西亚头像框,\
订阅期间有效", type=0, priority=2, openclose=1, param=0 },
	{ id=10009, name="暗夜之翼头像框", propdesc="由高超的技艺打造而成，完美复原了历史上传说中暗夜之翼，能赋予穿戴者勇气与智慧。", type=0, priority=31, openclose=0, param=0 },
	{ id=10010, name="樱花头像框", propdesc="迎风招展的樱花，带着诗和远方一起踏上征程。", type=0, priority=32, openclose=0, param=0 },
	{ id=10011, name="龙环头像框", propdesc="神秘的龙纹与尖锐的龙爪，优秀的做工使其价值不菲。", type=0, priority=33, openclose=0, param=0 },
	{ id=10012, name="赤金头像框", propdesc="火焰般热情的赤红色，搭配金色的双翼，只能用完美来形容了吧。", type=0, priority=34, openclose=0, param=0 },
	{ id=10013, name="会长头像框", propdesc="会长身份的标志，戴上它象征自己的身份吧。", type=0, priority=3, openclose=1, param=0 },
	{ id=10014, name="预注册头像框", propdesc="预注册玩家的象征，感谢您的支持！", type=0, priority=35, openclose=0, param=0 },
	{ id=10015, name="万圣节限时头像框", propdesc="头像框可从万圣节活动中限时获得。", type=0, priority=36, openclose=0, param=0 },
	{ id=10016, name="勇者之证头像框", propdesc="纳多大陆勇者身份的证明，请带着勇者的身份勇往直前吧！", type=0, priority=37, openclose=1, param=0 },
	{ id=10017, name="名人堂头像框", propdesc="幻境之塔名人堂身份的象征，本头像框仅限名人堂第一名获得。", type=0, priority=38, openclose=0, param=0 },
	{ id=10018, name="2021圣诞头像框", propdesc="头像框可从圣诞节活动中限时获得。", type=0, priority=39, openclose=1, param=0 },
	{ id=10019, name="GM头像框", propdesc="仅游戏管理员可获得，由官方统一发放。", type=0, priority=100, openclose=0, param=0 },
	{ id=10020, name="世界霸主头像框", propdesc="在虚空王座中独占鳌头，仅世界霸主可获得（有效期为一周）。", type=0, priority=20, openclose=0, param=0 },
	{ id=10021, name="荣耀骑士头像框", propdesc="虚空王座中的身份象征，仅荣耀骑士可获得（有效期为一周）。", type=0, priority=21, openclose=0, param=0 },
	{ id=10022, name="无畏勇者头像框", propdesc="虚空王座中的身份象征，仅无畏勇者可获得（有效期为一周）。", type=0, priority=22, openclose=0, param=0 },
	{ id=10023, name="闪电一刀头像框", propdesc="在虚空王座的世界BOSS挑战中最后击杀BOSS的玩家获得此头像框（有效期为一周）。", type=0, priority=23, openclose=0, param=0 },
	{ id=10024, name="2021新年头像框", propdesc="在2021新年活动中购买礼包限时获得。", type=0, priority=39, openclose=0, param=0 },
	{ id=10025, name="合金计划西亚头像框", propdesc="在2021情人节活动中购买西亚皮肤礼包获得", type=0, priority=40, openclose=0, param=0 },
	{ id=10026, name="征服王头像框", propdesc="公会争霸公会排名第一奖励，是最强公会的象征。", type=0, priority=41, openclose=0, param=0 },
	{ id=10027, name="统治者头像框", propdesc="公会争霸公会排名第二奖励，是强大公会的象征。", type=0, priority=42, openclose=0, param=0 },
	{ id=10028, name="骁勇者头像框", propdesc="公会争霸公会排名第三奖励，是团结公会的象征。", type=0, priority=43, openclose=0, param=0 },
	{ id=10029, name="龙首骑士头像框", propdesc="开服竞技[幻境之巅]中第一名获得", type=0, priority=43, openclose=1, param=0 },
	{ id=10030, name="龙脊骑士头像框", propdesc="开服竞技[幻境之巅]中第二名获得", type=0, priority=43, openclose=1, param=0 },
	{ id=10031, name="龙尾骑士头像框", propdesc="开服竞技[幻境之巅]中第三名获得", type=0, priority=43, openclose=1, param=0 },
	{ id=10032, name="超级领主专属头像框", propdesc="体现身份和实力不可抹灭的符号，必定刻入纳多大陆的历史长河中！", type=0, priority=43, openclose=1, param=0 },
	{ id=10033, name="巅峰冠军头像框", propdesc="巅峰赛赛季冠军头像框，在[巅峰排位-巅峰赛]达到赛季冠军的证明", type=0, priority=44, openclose=0, param=0 },
	{ id=10034, name="巅峰亚军头像框", propdesc="巅峰赛赛季亚军头像框，在[巅峰排位-巅峰赛]达到赛季亚军的证明", type=0, priority=45, openclose=0, param=0 },
	{ id=10035, name="巅峰季军头像框", propdesc="巅峰赛赛季季军头像框，在[巅峰排位-巅峰赛]达到赛季季军的证明", type=0, priority=46, openclose=0, param=0 },
	{ id=10036, name="巅峰十强头像框", propdesc="巅峰赛赛季十强头像框，在[巅峰排位-巅峰赛]达到赛季十强的证明", type=0, priority=47, openclose=0, param=0 },
	{ id=11001, name="闪耀黄金头像框", propdesc="闪耀黄金头像框，在排位赛达到闪耀黄金段位的证明", type=1, priority=15, openclose=1, param=19 },
	{ id=11002, name="梦幻白金头像框", propdesc="梦幻白金头像框，在排位赛达到梦幻白金段位的证明", type=1, priority=14, openclose=1, param=35 },
	{ id=11003, name="永恒钻石头像框", propdesc="永恒钻石头像框，在排位赛达到永恒钻石段位的证明", type=1, priority=13, openclose=1, param=51 },
	{ id=11004, name="至尊大师头像框", propdesc="至尊大师头像框，在排位赛达到至尊大师段位的证明", type=1, priority=12, openclose=1, param=76 },
	{ id=11005, name="最强王者头像框", propdesc="最强王者头像框，在排位赛达到最强王者段位的证明", type=1, priority=11, openclose=1, param=101 },
	{ id=11006, name="传说王者头像框", propdesc="传说王者头像框，在排位赛达到传说王者段位的证明", type=0, priority=10, openclose=1, param=0 },
	{ id=11007, name="巅峰冠军头像框", propdesc="巅峰赛赛季冠军头像框，在[巅峰排位-巅峰赛]达到赛季冠军的证明", type=0, priority=43, openclose=1, param=0 },
	{ id=11008, name="巅峰亚军头像框", propdesc="巅峰赛赛季亚军头像框，在[巅峰排位-巅峰赛]达到赛季亚军的证明", type=0, priority=43, openclose=1, param=0 },
	{ id=11009, name="巅峰季军头像框", propdesc="巅峰赛赛季季军头像框，在[巅峰排位-巅峰赛]达到赛季季军的证明", type=0, priority=43, openclose=1, param=0 },
	{ id=11010, name="巅峰十强头像框", propdesc="巅峰赛赛季十强头像框，在[巅峰排位-巅峰赛]达到赛季十强的证明", type=0, priority=43, openclose=1, param=0 },
	{ id=11011, name="征服王头像框", propdesc="公会争霸公会排名第一奖励，是最强公会的象征。", type=0, priority=41, openclose=1, param=0 },
	{ id=11012, name="统治者头像框", propdesc="公会争霸公会排名第二奖励，是强大公会的象征。", type=0, priority=42, openclose=1, param=0 },
	{ id=11013, name="骁勇者头像框", propdesc="公会争霸公会排名第三奖励，是团结公会的象征。", type=0, priority=43, openclose=1, param=0 }
}
return TbFrame