local TbGvgStronghold = {
	{ id=101, name="strongholdName1", type=1, portrait="touxiang1", buffShow={"0","attrFirst_4","20"}, buffShow2={"12","20"}, hpMultiple=26, buff=507, freeTimes=2, buyTimes=999, map="baiyanisibattlemap3", guildPoints=3000, guildPointsDeducted=450, personalPoints=5000, breakReward=0 },
	{ id=102, name="strongholdName2", type=1, portrait="touxiang2", buffShow={"attrFirst_3","attrFirst_5","15"}, buffShow2={"5","15","31","15"}, hpMultiple=26, buff=506, freeTimes=2, buyTimes=999, map="baiyanisibattlemap2", guildPoints=3000, guildPointsDeducted=450, personalPoints=5000, breakReward=0 },
	{ id=103, name="strongholdName3", type=1, portrait="touxiang3", buffShow={"0","attrFirst_6","20"}, buffShow2={"32","20"}, hpMultiple=26, buff=505, freeTimes=2, buyTimes=999, map="baiyanisibattlemap1", guildPoints=3000, guildPointsDeducted=450, personalPoints=5000, breakReward=0 },
	{ id=201, name="strongholdName4", type=2, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="shourenbattlemap3", guildPoints=30, guildPointsDeducted=10, personalPoints=800, breakReward=361 },
	{ id=202, name="strongholdName5", type=2, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="mofashanjibattlemap3", guildPoints=30, guildPointsDeducted=10, personalPoints=800, breakReward=362 },
	{ id=203, name="strongholdName6", type=2, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="patabattlemap", guildPoints=30, guildPointsDeducted=10, personalPoints=800, breakReward=363 },
	{ id=204, name="strongholdName7", type=2, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="tanxishamobattlemap3", guildPoints=30, guildPointsDeducted=10, personalPoints=800, breakReward=364 },
	{ id=205, name="strongholdName8", type=2, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="mofashanjibattlemap1", guildPoints=30, guildPointsDeducted=10, personalPoints=800, breakReward=365 },
	{ id=301, name="strongholdName9", type=3, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="tanxishamobattlemap2", guildPoints=5, guildPointsDeducted=0, personalPoints=160, breakReward=0 },
	{ id=302, name="strongholdName9", type=3, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="tanxishamobattlemap2", guildPoints=5, guildPointsDeducted=0, personalPoints=160, breakReward=0 },
	{ id=303, name="strongholdName9", type=3, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="tanxishamobattlemap2", guildPoints=5, guildPointsDeducted=0, personalPoints=160, breakReward=0 },
	{ id=304, name="strongholdName9", type=3, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="tanxishamobattlemap2", guildPoints=5, guildPointsDeducted=0, personalPoints=160, breakReward=0 },
	{ id=305, name="strongholdName9", type=3, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="tanxishamobattlemap2", guildPoints=5, guildPointsDeducted=0, personalPoints=160, breakReward=0 },
	{ id=306, name="strongholdName9", type=3, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="tanxishamobattlemap2", guildPoints=5, guildPointsDeducted=0, personalPoints=160, breakReward=0 },
	{ id=307, name="strongholdName9", type=3, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="tanxishamobattlemap2", guildPoints=5, guildPointsDeducted=0, personalPoints=160, breakReward=0 },
	{ id=308, name="strongholdName9", type=3, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="tanxishamobattlemap2", guildPoints=5, guildPointsDeducted=0, personalPoints=160, breakReward=0 },
	{ id=309, name="strongholdName9", type=3, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="tanxishamobattlemap2", guildPoints=5, guildPointsDeducted=0, personalPoints=160, breakReward=0 },
	{ id=310, name="strongholdName9", type=3, portrait="", buffShow={}, buffShow2={}, hpMultiple=0, buff=0, freeTimes=1, buyTimes=0, map="tanxishamobattlemap2", guildPoints=5, guildPointsDeducted=0, personalPoints=160, breakReward=0 }
}
return TbGvgStronghold